apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
- target:
    group: machineconfiguration.openshift.io
    version: v1
    kind: MachineConfig
    name: load-sctp-module
  path: sctp.yaml
