apiVersion: v1
kind: Namespace
metadata:
  name: cnfdt16-policies
  labels:
    name: cnfdt16-policies
---
apiVersion: ran.openshift.io/v1
kind: PolicyGenTemplate
metadata:
  name: "cnfdt16"
  namespace: "cnfdt16-policies"
spec:
  bindingRules:
    siteName: "cnfdt16"
  mcp: "master"
  sourceFiles:
    - fileName: SriovNetwork.yaml
      policyName: "sriov-nw-fh-policy"
      metadata:
        name: "sriov-nw-du-fh"
      spec:
        resourceName: du_fh
        vlan: 140
    - fileName: SriovNetworkNodePolicy.yaml
      policyName: "sriov-nnp-fh-policy"
      metadata:
        name: "sriov-nnp-du-fh"
      spec:
        deviceType: netdevice
        isRdma: true
        nicSelector:
          pfNames: ["ens5f0"]
        numVfs: 8
        priority: 10
        resourceName: du_fh
    - fileName: SriovNetwork.yaml
      policyName: "sriov-nw-mh-policy"
      metadata:
        name: "sriov-nw-du-mh"
      spec:
        resourceName: du_mh
        vlan: 150
    - fileName: SriovNetworkNodePolicy.yaml
      policyName: "sriov-nnp-mh-policy"
      metadata:
        name: "sriov-nnp-du-mh"
      spec:
        deviceType: vfio-pci
        isRdma: false
        nicSelector:
          pfNames: ["ens7f0"]
        numVfs: 8
        priority: 10
        resourceName: du_mh
    - fileName: PerformanceProfile.yaml
      policyName: "perfprofile-policy"
      metadata:
        name: openshift-node-performance-profile
      spec:
        cpu:
          isolated: "2-51,54-103"
          reserved: "0-1,52-53"
        hugepages:
          defaultHugepagesSize: 1G
          pages:
            - size: 1G
              count: 32
    - fileName: TunedPerformancePatch.yaml
      policyName: "tuned-perf-patch-policy"
      spec:
        profile:
          - name: performance-patch
            data: |
              [main]
              summary=Configuration changes profile inherited from performance created tuned
              include=openshift-node-performance-openshift-node-performance-profile
              [bootloader]
              cmdline_crash=nohz_full=2-51,54-103
              [sysctl]
              kernel.timer_migration=1
              [service]
              service.stalld=start,enable
