apiVersion: performance.openshift.io/v1
kind: PerformanceProfile
metadata:
  name: perf-example
spec:
  numa:
    topologyPolicy: "restricted"
  cpu:
    isolated: "2-51"
    reserved: "0-1"
  hugepages:
    defaultHugepagesSize: 1G
    pages:
    - count: 16
      size: 1G
      node: 0
  realTimeKernel:
    enabled: false
  nodeSelector:
    node-role.kubernetes.io/worker-cnf: ""    
