# Builder
FROM openshift/origin-release:golang-1.16 as builder
USER root
ENV PKG_ROOT=cnf-features-deploy
ENV PKG_PATH=/go/src/$PKG_ROOT
ENV POLGEN_ROOT=$PKG_PATH/ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator
RUN mkdir -p $PKG_PATH
WORKDIR $PKG_PATH/
ARG ZIP_NAME
COPY --chown=1001 $ZIP_NAME  $PKG_PATH/
RUN (unzip $ZIP_NAME || true) && rm $ZIP_NAME
WORKDIR $POLGEN_ROOT
RUN go build -mod=mod -o /PolicyGenerator

# Container image
FROM python:3.9-alpine
USER root
ENV WD=/usr/src/hook
RUN mkdir $WD
WORKDIR $WD

RUN apk update \
    && apk add jq \
    && rm -rf /var/cache/apk/* &&\
    python -m pip install --upgrade pip && \
    python -m pip install kubernetes jinja2

ARG TAR_NAME
COPY --from=builder  /PolicyGenerator $WD/
COPY --chown=1001 $TAR_NAME $WD/
RUN tar -xf $TAR_NAME
#COPY src/*  $WD
RUN chown -R 1001:1001 $WD
USER 1001

