---
apiVersion: policyGenerator/v1
kind: PolicyGenTemplate
metadata:
  # The name will be used to generate the placementBinding and placementRule names as {name}-placementBinding and {name}-placementRule
  name: "common-policies"
  namespace: "policy-template"
  labels:
    common: true
    groupName: "N/A"
    siteName: "N/A"
    mcp: "N/A"
sourceFiles:
  # Create operators policies that will be installed in all clusters
  - fileName: SriovSubscriptionLocal
    policyName: "sriov-sub-policy"
  - fileName: SriovSubscriptionNS
    policyName: "sriov-sub-ns-policy"
  - fileName: SriovSubscriptionOperGroup
    policyName: "sriov-sub-oper-policy"
  - fileName: PtpSubscriptionLocal
    policyName: "ptp-sub-policy"
  - fileName: PtpSubscriptionNS
    policyName: "ptp-sub-ns-policy"
  - fileName: PtpSubscriptionOperGroup
    policyName: "ptp-sub-oper-policy"
  - fileName: PaoSubscriptionLocal
    policyName: "pao-sub-policy"
  - fileName: PaoSubscriptionNS
    policyName: "pao-sub-ns-policy"
  - fileName: PaoSubscriptionOperGroup
    policyName: "pao-sub-oper-policy"
  - fileName: CatalogSourceLocal
    policyName: "catalog-source-policy"
  - fileName: ClusterLogSubscription
    policyName: "log-sub-policy"
  - fileName: MachineConfigContainerMountNS
    policyName: "worker-mc-mount-ns-policy"
    name: "02-worker-container-mount-namespace"
    labels:
      machineconfiguration.openshift.io/role: worker
  - fileName: disconnected-edge-cmap
    policyName: "disconnected-edge-cmap-policy"
  - fileName: disconnected-pull
    policyName: "disconnected-pull-policy"
  - fileName: ImageContentSourcePolicy
    policyName: "icsp-policy"
  - fileName: MachineConfigContainerMountNS
    policyName: "master-mc-mount-ns-policy"
    name: "02-master-container-mount-namespace"
    labels:
      machineconfiguration.openshift.io/role: master
