apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# DU-LDC networks
  - sriov-nw-ns.yaml
  - sriov-nnp-du-ldc-numa0-fh-dpdk.yaml
  - sriov-nnp-du-ldc-numa0-mh-dpdk.yaml
  - sriov-nnp-du-ldc-numa1-fh-dpdk.yaml
  - sriov-nnp-du-ldc-numa1-mh-dpdk.yaml
  - sriov-nw-du-ldc-numa0-fh.yaml
  - sriov-nw-du-ldc-numa0-mh-c.yaml
  - sriov-nw-du-ldc-numa0-mh-u.yaml
  - sriov-nw-du-ldc-numa1-fh.yaml
  - sriov-nw-du-ldc-numa1-mh-c.yaml
  - sriov-nw-du-ldc-numa1-mh-u.yaml




