apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: redhat-operators-disconnected
  namespace: openshift-marketplace
  annotations:
    target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
spec:
  sourceType: grpc
  image: dhcp19-17-10.clus2.t5g.lab.eng.bos.redhat.com:5000/redhat-operators-disconnected:latest
  displayName: redhat-operators-disconnected-catalog
  publisher: Red Hat
