apiVersion: operator.openshift.io/v1alpha1
kind: ImageContentSourcePolicy
metadata:
  name: redhat-operators-disconnected
spec:
  repositoryDigestMirrors:
  - mirrors:
    - dhcp-55-159.lab.eng.tlv2.redhat.com:5000/redhat-operators-catalog/openshift4-ose-local-storage-static-provisioner
    source: registry.redhat.io/openshift4/ose-local-storage-static-provisioner
  - mirrors:
    - dhcp-55-159.lab.eng.tlv2.redhat.com:5000/redhat-operators-catalog/openshift4-ose-sriov-network-config-daemon
    source: registry.redhat.io/openshift4/ose-sriov-network-config-daemon
  - mirrors:
    - dhcp-55-159.lab.eng.tlv2.redhat.com:5000/redhat-operators-catalog/openshift4-ose-local-storage-diskmaker
    source: registry.redhat.io/openshift4/ose-local-storage-diskmaker
  - mirrors:
    - dhcp-55-159.lab.eng.tlv2.redhat.com:5000/redhat-operators-catalog/openshift4-ose-sriov-network-device-plugin
    source: registry.redhat.io/openshift4/ose-sriov-network-device-plugin
  - mirrors:
    - dhcp-55-159.lab.eng.tlv2.redhat.com:5000/redhat-operators-catalog/openshift4-ose-ptp-operator
    source: registry.redhat.io/openshift4/ose-ptp-operator
  - mirrors:
    - dhcp-55-159.lab.eng.tlv2.redhat.com:5000/redhat-operators-catalog/openshift-logging-cluster-logging-rhel8-operator
    source: registry.redhat.io/openshift-logging/cluster-logging-rhel8-operator
  - mirrors:
    - dhcp-55-159.lab.eng.tlv2.redhat.com:5000/redhat-operators-catalog/openshift4-ose-sriov-cni
    source: registry.redhat.io/openshift4/ose-sriov-cni
  - mirrors:
    - dhcp-55-159.lab.eng.tlv2.redhat.com:5000/redhat-operators-catalog/openshift4-ose-sriov-network-operator
    source: registry.redhat.io/openshift4/ose-sriov-network-operator
  - mirrors:
    - dhcp-55-159.lab.eng.tlv2.redhat.com:5000/redhat-operators-catalog/openshift4-ose-sriov-infiniband-cni
    source: registry.redhat.io/openshift4/ose-sriov-infiniband-cni
  - mirrors:
    - dhcp-55-159.lab.eng.tlv2.redhat.com:5000/redhat-operators-catalog/openshift4-ose-local-storage-operator
    source: registry.redhat.io/openshift4/ose-local-storage-operator
  - mirrors:
    - dhcp-55-159.lab.eng.tlv2.redhat.com:5000/redhat-operators-catalog/openshift4-ose-sriov-network-webhook
    source: registry.redhat.io/openshift4/ose-sriov-network-webhook
  - mirrors:
    - dhcp-55-159.lab.eng.tlv2.redhat.com:5000/redhat-operators-catalog/openshift4-ose-ptp
    source: registry.redhat.io/openshift4/ose-ptp
  - mirrors:
    - dhcp-55-159.lab.eng.tlv2.redhat.com:5000/redhat-operators-catalog/openshift4-performance-addon-rhel8-operator
    source: registry.redhat.io/openshift4/performance-addon-rhel8-operator
  - mirrors:
    - dhcp-55-159.lab.eng.tlv2.redhat.com:5000/redhat-operators-catalog/openshift4-ose-kube-rbac-proxy
    source: registry.redhat.io/openshift4/ose-kube-rbac-proxy
  - mirrors:
    - dhcp-55-159.lab.eng.tlv2.redhat.com:5000/redhat-operators-catalog/openshift4-ose-sriov-dp-admission-controller
    source: registry.redhat.io/openshift4/ose-sriov-dp-admission-controller
  - mirrors:
    - dhcp-55-159.lab.eng.tlv2.redhat.com:5000/redhat-operators-catalog/openshift4-ose-sriov-operator-must-gather
    source: registry.redhat.io/openshift4/ose-sriov-operator-must-gather
  - mirrors:
    - dhcp-55-159.lab.eng.tlv2.redhat.com:5000/redhat-operators-catalog/openshift-logging-fluentd-rhel8
    source: registry.redhat.io/openshift-logging/fluentd-rhel8
