apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: performance-addon-operator
  namespace: openshift-performance-addon-operator
spec:
  channel: "4.8"
  name: performance-addon-operator
  source: redhat-operators-disconnected
  sourceNamespace: openshift-marketplace
