# Builder
FROM openshift/origin-release:golang-1.16
USER root
ENV PKG_ROOT=cnf-features-deploy
ENV PKG_PATH=/go/src/$PKG_ROOT
ENV POLGEN_ROOT=$PKG_PATH/ztp/resource-generator/src
RUN mkdir -p $PKG_PATH && \
    go get k8s.io/client-go@v0.21.1
WORKDIR $PKG_PATH/
ARG TAR_NAME
COPY --chown=1001 $TAR_NAME  $PKG_PATH/
RUN (tar -xf $TAR_NAME) && rm $TAR_NAME
# RUN go mod tidy && go mod vendor
WORKDIR $POLGEN_ROOT

