ARG BASE
FROM $BASE:latest
USER root
ENV WD=/usr/src/hook
RUN mkdir $WD
WORKDIR $WD

ARG TAR_NAME
COPY --chown=1001 $TAR_NAME $WD/
RUN tar -xvf $TAR_NAME ztp  && \
    rm $TAR_NAME && \
    chown -R 1001:1001 $WD
COPY --from=policygen  /PolicyGenerator $WD/ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator
COPY --from=hook /hook $WD/
WORKDIR $WD/ztp/resource-generator/src
USER 1001

