apiVersion: kustomize.config.k8s.io/v1alpha1  
kind: Component

resources:
  - ../../../common/patches/disable-chronyd

patches:
- target:
    group: machineconfiguration.openshift.io
    version: v1
    kind: MachineConfig
    name: disable-chronyd
  path: disable-chronyd.yaml
