apiVersion: v1
kind: Namespace
metadata:
  name: clusters-sub
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clusters
  namespace: openshift-gitops
spec:
  destination:
    namespace: clusters-sub
    server: https://kubernetes.default.svc
  project: ztp-app-project
  source:
    path: install
    repoURL: https://gitlab.cee.redhat.com/ran/lab-ztp.git
    targetRevision: hv6-hub
