apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
- behavior: replace
  files:
  - AcceleratorsNS.yaml
  - AcceleratorsOperGroup.yaml
  - AcceleratorsSubscription.yaml
  - ClusterLogCatSource.yaml
  - ClusterLogForwarder.yaml
  - ClusterLogOperGroup.yaml
  - ClusterLogSubscription.yaml
  - ClusterLogging.yaml
  - ConsoleOperatorDisable.yaml
  - DefaultCatsrc.yaml
  - DisableSnoNetworkDiag.yaml
  - DisconnectedICSP.yaml
  - MachineConfigAcceleratedStartup.yaml
  - MachineConfigChronyDynamicMaster.yaml
  - MachineConfigContainerMountNS.yaml
  - MachineConfigPool.yaml
  - MachineConfigSctp.yaml
  - OperatorHub.yaml
  - PaoSubscription.yaml
  - PaoSubscriptionCatalogSource.yaml
  - PaoSubscriptionNS.yaml
  - PaoSubscriptionOperGroup.yaml
  - PerformanceProfile.yaml
  - PtpCatSource.yaml
  - PtpConfigMaster.yaml
  - PtpConfigSlave.yaml
  - PtpConfigSlaveCvl.yaml
  - PtpSubscription.yaml
  - PtpSubscriptionNS.yaml
  - PtpSubscriptionOperGroup.yaml
  - ReduceMonitoringFootprint.yaml
  - SriovCatSource.yaml
  - SriovNetwork.yaml
  - SriovNetworkNodePolicy.yaml
  - SriovOperatorConfig.yaml
  - SriovSubscription.yaml
  - SriovSubscriptionNS.yaml
  - SriovSubscriptionOperGroup.yaml
  - StorageCatSource.yaml
  - StorageLV.yaml
  - StorageNS.yaml
  - StorageOperGroup.yaml
  - StorageSubscription.yaml
  - TunedPerformancePatch.yaml
  name: source-crs
